server:
  port: 8082
  contextPath: /task-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

# When enabled=false, traces log to the console. Comment to send to zipkin
sample:
  zipkin:
    enabled: true

# Note that we will use the JWT token to get user data
security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmpvTtDgIkbUmVimQAmBh
          HDcrzqh1MttPntRVecSbA5VzXRZ04oPP1QgxyP9dNVve2ptRfW+zvk6oCJLQaqw5
          W3MOiX9yHxpugHm1lc9KjQmTiBlu4i7hmQxwVD8QjljYbXwxDwb4xn9lw0KXPjl9
          kL/JVc0PaKjMSRzDprxXWbfMhseWsSbG0VXFBIuStoqY13z0salkQTK81R+6WQAN
          k1woVbBQlUemw1l5y9I6Er2RK0/nw9ybDOc5dcUNJAk9jzYVg1GFulvk0RCirMHA
          2c8CZqjp7a90rFHbSN1tGpoOtdWqQRDSlDAYjj2rHWYs8ZpSlLHS1h77c2ZXqQJy
          zQIDAQAB
          -----END PUBLIC KEY-----
---
# task-webservice instance when used on Docker
spring:
  profiles: docker
  zipkin:
    baseUrl: http://zipkinserver:9411/

eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eurekaregistry:8761/eureka/

# Define the port where the API gateway server would be running. This could always be port 8080
# since each docker container has it's own IP
server:
  port: 8080
